name: Terraform Workflow

on:
  push:
    branches:
      - 'customer-*'
      - 'shared-*'
  pull_request:
    branches:
      - 'customer-*'
      - 'shared-*'


jobs:
  plan-and-apply:
    uses: philkrause/team-workflows/.github/workflows/terraform.yaml@main